### ISSUE TITLE
"null" title while shared article from searching result

### ISSUE THREAD

**Issue by Harlber** [Harlber/Moose#47]
As title said.

**Comment by Harlber** [comment]
v0.7 release

**Comment by xingstarx** [comment]
有个疑问，应用首页，点击搜索之后，从MainActivity进入SearchActivity,有内容之后，点击列表进入ArticleViewActivity了，但是我点击返回怎么直接变成了MainActivity

这样处理好吗，我感觉应该还是回到了SearchActivity才对吧

**Comment by Harlber** [comment]
有道理

**Comment by xingstarx** [comment]
done

**Comment by Harlber** [comment]
"null" title while shared article from searching result still exist.
